##
## Build
##

FROM golang:1.18-buster AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go ./

RUN go build -o /grpc-echo

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /grpc-echo /grpc-echo

USER nonroot:nonroot

ENTRYPOINT ["/grpc-echo"]