---
name: ci

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: arm64
    steps:
      -
        name: checkout workspace
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: list files in workspace
        run: ls -R
        working-directory: ${{ github.workspace }}/
      -
        name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      -
        name: build
        run: |
          go build -v
      -
        name: version
        run: echo "::set-output name=version::$(./grpc-echo version)"
        id: version
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.multistage
          platforms: ${{ matrix.arch }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/grpc-echo:latest,${{ secrets.DOCKER_HUB_USERNAME }}/grpc-echo:${{ steps.version.outputs.version }}
